In [1]:
import pandas as pd
# Drug_info_release.csv is untinteresting
pd.read_csv("Sanger_molecular_data/cell_info.csv")

,Sanger.Name,CCLE.Name,Alternative.Name,Disease.Area,Tissue..General.,COSMIC
0,22RV1,22RV1_PROSTATE,22RV1,Urology,male genital system,924100
1,647-V,647V_URINARY_TRACT,647V,Urology,urinary tract,906797
2,A549,A549_LUNG,A549,Lung,lung,905949
3,BFTC-905,BFTC905_URINARY_TRACT,BFTC905,Urology,urinary tract,910926
4,BT-20,BT20_BREAST,BT20,Breast,breast,906801
...,...,...,...,...,...,...
80,TCCSUP,TCCSUP_URINARY_TRACT,TCCSUP,Urology,urinary tract,687459
81,UACC-812,UACC812_BREAST,UACC812,Breast,breast,910910
82,UM-UC-3,UMUC3_URINARY_TRACT,UMUC3,Urology,urinary tract,724838
83,VCaP,VCAP_PROSTATE,VCAP,Urology,male genital system,1299075
84,VM-CUB-1,VMCUB1_URINARY_TRACT,VMCUB1,Urology,urinary tract,909780

In [12]:
gex = pd.read_csv("Sanger_molecular_data/gex.csv")
gex.dropna()

,Unnamed: 0,22RV1,647-V,A549,BFTC-905,BT-20,BT-474,BT-549,C32,CAL-120,...,SW837,SW900,SW948,T-24,T47D,TCCSUP,UACC-812,UM-UC-3,VCaP,VM-CUB-1
0,TSPAN6,4.804487,8.713556,8.495961,7.813436,7.971621,5.178131,6.383148,5.542645,7.632023,...,8.141044,7.755154,7.709982,7.788981,7.342996,7.401340,7.086304,6.410431,5.348023,7.187071
1,TNMD,2.848128,2.834723,2.886997,2.879330,2.792528,3.015506,2.746627,2.736643,2.964585,...,2.911450,2.816921,3.212680,2.984905,2.819535,2.724977,2.952920,2.795879,2.988278,2.691417
2,DPM1,10.331994,10.504748,9.643436,10.272719,10.601207,10.548792,10.392289,9.890112,10.379553,...,10.072444,10.214976,10.170757,10.558936,10.786582,9.864280,11.536803,10.326887,9.000925,10.184775
3,SCYL3,5.145387,3.792188,4.154471,4.050385,5.622674,5.829252,3.802817,3.346422,3.614794,...,4.531813,4.388774,4.606470,3.789149,4.677363,3.843770,4.520248,3.512380,4.306414,3.512961
4,C1orf112,3.545193,3.946664,3.307310,3.701491,3.740521,3.800657,4.379548,3.067727,3.380681,...,3.619282,3.946621,3.858040,3.674749,3.482290,4.383248,3.324127,3.291974,3.414812,3.823379
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17414,PPY2,3.080394,3.233059,3.036383,2.970800,2.991137,3.040448,3.144031,3.069556,2.997054,...,3.219672,3.226851,3.311019,3.190357,3.295970,3.244465,3.135298,3.407639,3.299581,3.109451
17415,KRT18P55,3.378913,3.648132,3.259655,3.386533,3.554597,3.136316,3.083726,3.062048,3.331134,...,3.012350,3.161274,3.344123,3.785186,3.082722,3.045701,3.735873,3.385810,3.335831,3.589427
17416,POLRMTP1,3.191797,3.022160,2.934753,2.931548,3.168497,3.024960,3.406266,3.185092,3.130696,...,2.837757,2.829626,3.079624,3.078025,2.995339,3.057605,2.853571,3.321254,3.386745,3.469339
17417,UBL5P2,9.466545,9.267838,9.174437,9.781957,9.235654,9.594467,9.333854,9.839337,9.986616,...,8.125303,9.471560,9.272901,9.385839,9.217796,9.246567,9.616495,8.601714,8.319282,9.270088
17418,TBC1D3P5,3.214997,3.340621,3.450427,3.052209,3.299910,3.340264,3.438851,3.207780,3.073724,...,3.198928,3.192203,3.525726,3.350846,3.437583,3.247812,3.523841,3.519523,3.364994,3.445858

Looks like the first file contains the 85 different cell lines and and the second one 17k genes with values of their expression in all cell lines <br>
And then we have 75k mutations with details which gene is mutated and to which tumor it led

In [14]:
pd.read_csv("Sanger_molecular_data/mutations.csv").iloc[1]

Gene.name                                                         LILRB1
Accession.Number                                         ENST00000396331
Gene.CDS.length                                                     1953
HGNC.ID                                                           6605.0
cell_line_name                                                   HCC1806
ID_sample                                                         907047
ID_tumour                                                         824559
Primary.site                                                      breast
Site.subtype                                                          NS
Primary.histology                                              carcinoma
Histology.subtype                                       ductal_carcinoma
Genome.wide.screen                                                     y
Mutation.ID                                                   COSM162161
Mutation.CDS                                                   c.1690G>A
Mutation.AA                                                      p.E564K
Mutation.Description                             Substitution - Missense
Mutation.zygosity                                                    het
GRCh                                                                  38
Mutation.genome.position                            19:54636536-54636536
strand                                                                 +
SNP                                                                    n
FATHMM.prediction                                        PASSENGER/OTHER
Mutation.somatic.status     Reported in another cancer sample as somatic
Pubmed_PMID                                                          NaN
ID_STUDY                                                             NaN
Institute                        American Type Culture Collection (ATCC)
Institute.Address                 P.O. Box 1549, Manassas, VA 20108, USA
Catalogue.Number                                                CRL-2335
Sample.source                                                  cell-line
Tumour.origin                                                    primary
Age                                                                 60.0
Comments                                               Grade:II,Stage:II
Name: 1, dtype: object

CNV = Copy Number Variation

In [15]:
pd.read_csv("Sanger_molecular_data/cnv/cnv_segment.csv")

,cell_line_name,sample_id,SNPstart,SNPend,chr_38,startpos_38,endpos_38,chr_37,startpos_37,endpos_37,minorCN,totalCN
0,NCI-H522,905944,1,14597,1,61736,25256851,1,61736,25583342,1,3
1,NCI-H522,905944,14598,14626,1,25266638,25320456,1,25593129,25646947,0,0
2,NCI-H522,905944,14627,17248,1,25320496,30457588,1,25646987,30930435,0,2
3,NCI-H522,905944,17249,44053,1,30457632,72302816,1,30930479,72768499,1,3
4,NCI-H522,905944,44054,44099,1,72303234,72345466,1,72768917,72811149,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
31657,KMS-11,1659817,1868236,1868488,-,-,-,Y,28678434,59020611,0,2
31658,KMS-11,1659817,1868489,1868490,Y,56874486,56874570,Y,59020633,59020717,0,0
31659,KMS-11,1659817,1868491,1868551,Y,56874769,56884760,Y,59020916,59030907,0,3
31660,KMS-11,1659817,1868552,1868553,Y,56884768,56884769,Y,59030915,59030916,0,0
31661,KMS-11,1659817,1868554,1868570,Y,56884775,56886662,Y,59030922,59032809,0,2

In [17]:
pd.read_csv("Sanger_molecular_data/cnv/cnv_gene.csv")

/home/stefanhuber3125/.local/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3170: DtypeWarning: Columns (2,9) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,cell_line_name,gene,chr_GRCh38,gene_start_GRCh38,gene_end_GRCh38,max_cn_GRCh38,min_cn_GRCh38,zygosity_GRCh38,disruption_status_GRCh38,chr_GRCh37,gene_start_GRCh37,gene_end_GRCh37,max_cn_GRCh37,min_cn_GRCh37,zygosity_GRCh37,disruption_status_GRCh37
0,22RV1,39340,1,86880690.0,86914111.0,2.0,2.0,H,-,1,87346373,87379794,2,2,H,-
1,647-V,39340,1,86880690.0,86914111.0,-1.0,-1.0,-,-,1,87346373,87379794,3,3,H,-
2,A549,39340,1,86880690.0,86914111.0,2.0,2.0,L,-,1,87346373,87379794,2,2,L,-
3,BFTC-905,39340,1,86880690.0,86914111.0,3.0,3.0,H,-,1,87346373,87379794,3,3,H,-
4,BT-20,39340,1,86880690.0,86914111.0,2.0,2.0,H,-,1,87346373,87379794,2,2,H,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2478425,TCCSUP,mir-424,X,134546614.0,134546711.0,2.0,2.0,L,-,X,133680644,133680741,2,2,L,-
2478426,UACC-812,mir-424,X,134546614.0,134546711.0,5.0,5.0,H,-,X,133680644,133680741,5,5,H,-
2478427,UM-UC-3,mir-424,X,134546614.0,134546711.0,2.0,2.0,L,-,X,133680644,133680741,2,2,L,-
2478428,VCaP,mir-424,X,134546614.0,134546711.0,2.0,2.0,L,-,X,133680644,133680741,2,2,L,-
2478429,VM-CUB-1,mir-424,X,134546614.0,134546711.0,1.0,1.0,L,-,X,133680644,133680741,1,1,L,-